export const homeUrl = "https://dev.bluelight.inc/"
export const topHeaderLinks = new Set(['https://twitter.com/bluelightworlds', 'https://discord.gg/bluelightworlds',
    'https://t.me/bluelightworlds', 'https://cryptology.com/trading/KALE_USDT'])
export const mainHeaderBlankLinks = new Set(['https://docs.bluelight.inc/', 'https://bluelightworlds.medium.com/'])
export const mainHeaderLinks = ['/team', '/faq', '/market', '/']
export const cookiePopupLink = '/privacy-policy'
export const partnersLinks = new Set(['https://alohabrowser.com/', 'https://toonbox.studio/', 'https://tmm.world/blog',
    'http://dragonslake.com/', 'https://cryptology.com/', 'https://coinmarketcap.com/currencies/bluelight/',
    'https://www.coingecko.com/en/coins/bluelight', 'https://nftdesignawards.io/'])
export const topFooterBlankLinks = new Set(['https://docs.bluelight.inc/',
    'https://static.bluelight.inc/files/BlueLight_PressKit.pdf', 'https://docs.bluelight.inc/economy/game-token-kale'])
export const topFooterLinks = ['/team', '/faq', '/terms-of-service', '/privacy-policy', '/']
export const bottomFooterlinks = new Set(['https://viewpointlabs.io/', 'https://twitter.com/bluelightworlds',
    'https://discord.gg/bluelightworlds', 'https://t.me/bluelightworlds', 'https://www.instagram.com/bluelightworlds/',
    'https://www.youtube.com/channel/UCCPGjsqqZVDVIqCOFjSiAHg', 'https://www.facebook.com/bluelightworlds',
    'https://bluelightworlds.medium.com/', 'https://www.reddit.com/r/bluelightworlds/'])

export const mainPageAllLinks = new Set([
    "https://twitter.com/bluelightworlds",
    "https://discord.gg/bluelightworlds",
    "https://t.me/bluelightworlds",
    "https://cryptology.com/trading/KALE_USDT",
    "https://dev.bluelight.inc/",
    "https://dev.bluelight.inc/market",
    "https://bluelightworlds.medium.com/",
    "https://dev.bluelight.inc/team",
    "https://docs.bluelight.inc/",
    "https://dev.bluelight.inc/faq",
    "https://dev.bluelight.inc/auth",
    "https://dev.bluelight.inc/market",
    "https://bluelightworlds.medium.com/",
    "https://dev.bluelight.inc/team",
    "https://docs.bluelight.inc/",
    "https://dev.bluelight.inc/faq",
    "https://tmm.world/blog",
    "https://alohabrowser.com/",
    "http://dragonslake.com/",
    "https://toonbox.studio/",
    "https://coinmarketcap.com/currencies/bluelight/",
    "https://cryptology.com/",
    "https://www.coingecko.com/en/coins/bluelight",
    "https://nftdesignawards.io/",
    "https://dev.bluelight.inc/privacy-policy",
    "https://dev.bluelight.inc/",
    "https://twitter.com/bluelightworlds",
    "https://discord.gg/bluelightworlds",
    "https://t.me/bluelightworlds",
    "https://bluelightworlds.medium.com/",
    "https://www.youtube.com/channel/UCCPGjsqqZVDVIqCOFjSiAHg",
    "https://www.facebook.com/bluelightworlds",
    "https://www.reddit.com/r/bluelightworlds/",
    "https://www.instagram.com/bluelightworlds/",
    "https://dev.bluelight.inc/terms-of-service",
    "https://dev.bluelight.inc/privacy-policy",
    "https://static.bluelight.inc/files/BlueLight_PressKit.pdf",
    "https://dev.bluelight.inc/faq",
    "https://dev.bluelight.inc/team",
    "https://docs.bluelight.inc/",
    "https://docs.bluelight.inc/economy/game-token-kale",
    "https://dev.bluelight.inc/terms-of-service",
    "https://dev.bluelight.inc/privacy-policy",
    "https://static.bluelight.inc/files/BlueLight_PressKit.pdf",
    "https://dev.bluelight.inc/faq",
    "https://dev.bluelight.inc/team",
    "https://docs.bluelight.inc/",
    "https://docs.bluelight.inc/economy/game-token-kale",
    "https://dev.bluelight.inc/team",
    "https://docs.bluelight.inc/",
    "https://static.bluelight.inc/files/BlueLight_PressKit.pdf",
    "https://dev.bluelight.inc/faq",
    "https://dev.bluelight.inc/terms-of-service",
    "https://dev.bluelight.inc/privacy-policy",
    "https://docs.bluelight.inc/economy/game-token-kale",
    "https://viewpointlabs.io/",
    "https://twitter.com/bluelightworlds",
    "https://discord.gg/bluelightworlds",
    "https://t.me/bluelightworlds",
    "https://bluelightworlds.medium.com/",
    "https://www.youtube.com/channel/UCCPGjsqqZVDVIqCOFjSiAHg",
    "https://www.facebook.com/bluelightworlds",
    "https://www.reddit.com/r/bluelightworlds/",
    "https://www.instagram.com/bluelightworlds/"
])
