export const topHeaderMainPageLinks = '.Header_root__m8f7i a'
export const mailHeaderAllLinks = '.Menu_staticMenu__UujBR a'
export const mailHeaderExternalLinks = '.Menu_staticMenu__UujBR a[target="_blank"]'
export const playNowButton = '[data-testid=button-header-play]'
export const privacyPopupButton = 'Accept'
export const privacyPopupText = '.alert_info__KyveJ a'
export const applyButton = '[data-testid="button-main-banner-play-now"]'
export const startJourney = '[data-testid="button-arrow-start-journey"]'
export const buildTeam = '[data-testid="button-arrow-build-team"]'
export const setUpAnOffice = '[data-testid="button-arrow-set-up-office"]'
export const partnershipLinks = '.Partners_partners__SRVHe a'
export const topFooter = '.Footer_menu__nr2tj a'
export const topFooterExternalLinks = '.Footer_menu__nr2tj a[target="_blank"]'
export const bottomFooter = '.Footer_social__2ggkK a'

